# Generated by Django 5.0.3 on 2024-03-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='video_url',
        ),
    ]
