# Generated by Django 5.0.3 on 2024-03-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0011_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='author',
        ),
    ]
