# Generated by Django 5.0.3 on 2024-03-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeinfo', '0002_remove_recipe_image_remove_recipe_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipe_images/'),
        ),
    ]
